### ISSUE TITLE
I found the typo

### ISSUE THREAD

**Issue by a-know** [hurutoriya/hurutoriya.github.io#6]
Hi. I found some typo on your site https://shunyaueta.com/ , so open this issue.

https://github.com/hurutoriya/hurutoriya.github.io/blob/915b90fe613c2abbae352622020ae55cf948a0be/data/config/widgets.toml#L4

https://github.com/hurutoriya/hurutoriya.github.io/blob/0a76fed05d9e7c100693b5f4aa2d71dee26a05b0/content/posts/2020-04-19/index.md#L7

https://github.com/hurutoriya/hurutoriya.github.io/blob/ee83aea7769714f1c66b7ed5d39cabb4b250fd3d/content/about.md#L7

I think `Leraing` -> `Learing` . Thanks :)

**Comment by hurutoriya** [comment]
Thanks @a-know !

**Comment by hurutoriya** [comment]
Fix now.
https://github.com/hurutoriya/hurutoriya.github.io/commit/3d932fa938396d5789c0e3955e53224a380be7d1
 Thanks for report 😄
